hetznercloud/hcloud-cloud-controller-manager

- hcloud/instances.go
- hcloud/instances_test.go
Deleting a running hetzner node will cause a nil pointer dereference when InstanceShutdownByProviderID is called for that node. This is caused by the fact that GetByID will return nil and not an error for the requested server.
> Fix node deletion for removed instances

- deploy/development-networks.yaml
- deploy/development.yaml
Kubernetes v1.16 removed some deprecated apiVersions. This commit updates the latest deployment files to be v1.16 compatible.
Fixes #24
> Update deployment files for k8s v1.16

- CHANGELOG.md
- README.md
- deploy/v1.5.2-networks.yaml
- deploy/v1.5.2.yaml
- hcloud/cloud.go
- hcloud/routes.go
hcloud-go returns nil but no error if the network was not found by name. This
in turn leads to a panic once it is tried to reload the network by ID.
> Fix nil pointer dereference error

- CHANGELOG.md
- go.mod
- go.sum
- hcloud/cloud.go
Fix nil pointer dereference when a network was not found, this fixes #60 
It also updates the hcloud-go to the latest version
> Fix nil pointer dereference when a network was not found

- docs/deploy_with_networks.md
The previous two steps could not work since they tried to create the same secret twice. The secret must be created in one step.
> Fix secret creation in deploy with networks guide.

- docs/deploy_with_networks.md
Currently the guide is hard to follow in regards of getting cilium to run properly.
This aims to add the required minimum configmap settings to get cilium to provide a network for the cluster.
> Add more comprehensive cilium examples

- README.md
- e2etests/e2e_test.go
- e2etests/setup.go
- e2etests/testing.go
- scripts/e2etest-local.sh
This allows manual analysis of the environment after a test failure.
> Add option to keep server after e2e test failure

- internal/annotation/load_balancer.go
The backend API does not support the operations that changing those
values would represent.
Closes #126
> Changing location or network zone has no effect

- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_test.go
- internal/mocks/loadbalancer.go
Up until now the disable-public-network annotation only affected newly
created Load Balancers. This commit implements modifying existing Load
Balancers upon changing the annotation.
Closes #127
> Update of disable-public-network annotation

- hcloud/cloud.go
- hcloud/load_balancers.go
- hcloud/load_balancers_test.go
- hcloud/testing.go
- internal/hcops/errors.go
- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_test.go
- internal/hcops/mocks.go
- internal/mocks/casts.go
- internal/mocks/loadbalancer.go
This commit adds a hcloud-ccm/service-uid label with the value of the
Kubernetes service UID to each Load Balancer created by the CCM. This
allows to uniquely identify Load Balancers managed by the CCM.
All Load Balancer related operations now use the Kubernetes service UID
to obtain the affected Load Balancer from the Hetzner Cloud Backend.
Thereby, renaming of Load Balancers can now be implemented properly as
the CCM does not need to know the old name of the Load Balancer anymore.
To allow the import of existing load balancers the CCM falls back to the
load-balancer.hetzner.cloud/name if no hcloud-ccm/service-uid label is
set. In this case it adds the label to the Load Balancer during
reconciliation.
Closes #128
> Identify Load Balancers by K8S service UID

- e2etests/e2e_test.go
- e2etests/setup.go
- e2etests/testing.go
- hcloud/load_balancers.go
- hcloud/load_balancers_test.go
This commit re-enables the IPv6 support for Load Balancers managed by
the Cloud Controller Manager. From this commit on Load Balancers are
always created with an IPv4 and an IPv6 address.
Closes #121 
This MR is from @fhofherr, i just have the honor to push it to Github and merge it :)
> Re-enable IPv6 support

- .github/workflows/test_e2e.yml
- .gitlab-ci.yml
- README.md
- e2etests/setup.go
- e2etests/templates/cloudinit_k3s.txt.tpl
- e2etests/templates/cloudinit_k8s.txt.tpl
- e2etests/testing.go
- scripts/e2etest-local.sh
This MR adds automated testing of the Cloud Controller Manager on k3s. It also removes the testing without Network Support, because the same tests are performed already when testing with Network support.
> Test Cloud Controller Manager on k3s 

- .gitignore
- hcloud/load_balancers.go
- internal/hcops/load_balancer.go
This improves the situation when you have a large cluster and add a Load Balancer to them. ATM, when you have more nodes than the maximal number of targets your LB type accepts, the reconciliation failed. This led more or less to a reconciliation loop.
Closes #149
> Improve Load Balancer Target Reconcilation

- README.md
- deploy/ccm-networks.yaml
- deploy/ccm.yaml
- deploy/dev-ccm-networks.yaml
- deploy/dev-ccm.yaml
rbac.authorization.k8s.io/v1beta1 has been deprecated since Kubernetes 1.17 and will be removed with 1.22. This change does not change the compatibility of the cloud controller manager as it only touches the current example deployment yaml files.
While I was at it I noticed the broken links in the readme, so I took the liberty to fix those in the same PR (but separate commit).
> Api deprecations in deployment yamls

- hcloud/util.go
These two lines are responsible for the most issues we got. We want to improve it a bit more and therefore add a logging line above the error line to help the users directly.
> Add log messages to give users a hint for the problem.

- .github/workflows/test_e2e.yml
- .gitlab-ci.yml
- README.md
- scripts/e2etest-local.sh
> Remove testing for k8s 1.18 (and k3s 1.18) as written in our Versioning policy

- deploy/ccm-networks.yaml
- deploy/ccm.yaml
Issue: The latest release 1.9.0 still references 1.8.1 in the deployment yaml files.
This PR would fix it at least on the master branch (so that the instructions in the readme file pull in the latest version, which is the expectation). But probably 1.9.1 should be released instead so that the git tag can also contain this change (then with v1.9.1, obviously). So feel free to reject this PR if you want to go for the 1.9.1 release directly.
> Fix version tag in deploy folder

- CHANGELOG.md
- deploy/ccm-networks.yaml
- deploy/ccm.yaml
- hcloud/cloud.go
When creating the 1.9.0 release it was forgotten to update the example
version numbers. This commit prepares the 1.9.1 release which sets the
correct version number in all files.
> Update version number in examples

- deploy/ccm-networks.yaml
- deploy/ccm.yaml
- deploy/dev-ccm-networks.yaml
- deploy/dev-ccm.yaml
The Kubernetes project is moving away from offensive wording and as part
of this KEP-2067 was accepted to replace the
`node-role.kubernetes.io/master:NoSchedule` taint with
`node-role.kubernetes.io/control-plane:NoSchedule`.
To be compatible with clusters that already use the new taint this pull
request adds an additional toleration for it. This change can't really
break existing setups because we continue to tolerate the old taint as
well.
Additional links:
- https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md
- https://github.com/kubernetes/enhancements/issues/2067
- https://github.com/kubernetes/kubeadm/issues/2200
> Tolerate node-role.kubernetes.io/control-plane:NoSchedule taints

- .goreleaser.yml
This supersedes the 1.10.0-rc1 release which only contained a
ccm-networks.yaml. Otherwise both releases are identical.
> Fix generation of deployment yamls

- hcloud/load_balancers.go
- hcloud/load_balancers_test.go
- internal/annotation/load_balancer.go
Enabling IPv6 by default in #137 broke clusters using external-dns. This
commit adds an option to disable IPv6 by setting the
load-balancer.hetzner.cloud/ipv6-disabled
annotation to true.
Closes #191
> Add option to disable IPv6 for load balancers

- docs/deploy_with_networks.md
The command `hcloud networks` does not exist, it should be `hcloud network`, now fixed.
> Fix for typo in hcloud command

- e2etests/testing.go
- go.mod
- go.sum
- hcloud/cloud.go
- hcloud/cloud_test.go
We had several reports/issues from customers who configured there CCM wrong. They copied there configuration and changed nothing (It uses the same API token and the configured network as the other cluster). However, the servers of the new cluster were in a different project and/or attached to a different network. Because of this, two CCM instances started to fight against each other, because the CCM always tries to reach the wanted state in the network, so it detaches everything it does not know about and then attaches his "known" routes.
With this MR we now check if the master is attached to the configured network by using a "not user controllable" source of truth - our metadata service, that is only reachable through the node public interface. This check will be performed on boot and if …
> Add Master is attached to configured Network check on controller boot.

- hcloud/cloud.go
- hcloud/instances.go
- hcloud/instances_test.go
This PR adds support for setting an IPv6 address of the node for IPv6-only and dualstack clusters behind an optional environment variable which defaults to IPv4-only.
Context is [this Terraform module](https://github.com/tibordp/terraform-hcloud-dualstack-k8s) which sets up a dual-stack cluster on Hetzner Cloud. The [network plugin](https://github.com/tibordp/wigglenet) that it uses needs instance addresses in order to identify where to terminate the Wireguard tunnel for pod-to-pod traffic and if the primary address family for the cluster is IPv6, it makes sense for the ExternalIP addresses to be also.
> Support for IPv6 NodeAddresses

- .goreleaser.yml
Currently the generated release assets (`ccm.yaml` and `ccm-networks.yaml`) do not include the "v" prefix of the build docker image tag.
e.g. for current release (v1.11.0):
https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.11.0/ccm.yaml (image tag without "v" prefix)
https://hub.docker.com/layers/hetznercloud/hcloud-cloud-controller-manager/v1.11.0/images/sha256-3e6f91a79693a9b7deaa415b89513919fd734c1a444e16eca9cfbe9cc82cb7c9 (image tag with "v" prefix)
> fix release asset version for docker image tag

- README.md
- hcloud/util.go
Add an explanation to the README explaining why a deprecation warning may occur. Once Kubernetes 1.23 is ready we will need to look into how this is supposed to work in the future. At the moment it seems like the cloud provider flag is going to be [removed completely](https://github.com/kubernetes/kubernetes/pull/90408#issuecomment-670057176) and can just be left out.
Closes #189
> Explain --cloud-provider=external a bit more

- hcloud/cloud.go
- hcloud/routes.go
Sometimes it might happen that routes still exists but the servers to the route are deleted. With this can handle this case easily.
Fixes #225
Fixes #231
Fixes #165
> Ignore stale routes on RouteList

- hcloud/cloud.go
- hcloud/cloud_test.go
- hcloud/load_balancers.go
- hcloud/testing.go
To implement my own feature request #233 and inspired by @fynluk's take in #236
Unfortunately #236 doesn't work for me, so here's my version.
This models the HCLOUD_LOAD_BALANCERS_DISABLE_IPV6 feature more closely
after how HCLOUD_LOAD_BALANCERS_DISABLE_PRIVATE_INGRESS is implemented.
@LKaemmerling @fhofherr I noticed EnsureLoadBalancer() returns the private ingress if enabled while GetLoadBalancer() does not. Is this intentional?
> Bring IPv6 flag in line with private ingress flag

- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_internal_test.go
> Health Check: Set healthcheck port to destination port if no port was not defined via annotation

- deploy/ccm-networks.yaml
- deploy/ccm-networks.yaml.tmpl
- deploy/ccm.yaml
- deploy/dev-ccm-networks.yaml
- deploy/dev-ccm.yaml
The default value for `operator` is `Equal`, but this doesn't provide
any value to check against, causing this to not be scheduled on control
plane nodes with the following taint:
```
- effect: NoSchedule
key: node-role.kubernetes.io/control-plane
value: "true"
```
Setting the operator to `Exists` will cause this to be scheduled.
> deploy: add missing operator: Exists

- README.md
- internal/annotation/load_balancer.go
- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_test.go
- internal/mocks/loadbalancer.go
This allows setting reverse DNS records for the Load Balancer with the annotations:
* `load-balancer.hetzner.cloud/ipv4-rdns` for IPv4 and
* `load-balancer.hetzner.cloud/ipv6-rdns` for IPv6.
As this is my first time working with testify and contributing to this repo, please check the tests I wrote carefully.
They pass, but some feedback if I wrote them correctly would be much appreciated, especially regarding the repeated type conversions in the mocks.
> feat: allow setting of reverse DNS records

- go.mod
- hcloud/cloud.go
- hcloud/cloud_test.go
- hcloud/instances.go
- hcloud/load_balancers.go
- hcloud/routes.go
- hcloud/util.go
- hcloud/zones.go
- internal/annotation/load_balancer.go
- internal/annotation/name.go
- internal/hcops/certificates.go
- internal/hcops/load_balancer.go
- internal/hcops/server.go
- internal/metrics/metrics.go
Provide metrics for Hetzner API calls; helps identifying slowness, throttling causes, and errors bursts.
Signed-off-by: Maksim Paskal <paskal.maksim@gmail.com>
> Metrics for Hetzner API calls

- internal/hcops/server.go
To update the internal cache, the provider is getting all servers of the corresponding project / user. For that, the /servers endpoint is called with page max page size of 50 per call.
But there is an internal timeout of 5s for that calls. And right now, if there is a user with more than 50+ server, one call need more time than 5s.
As a quick fix, we raise the timeout. Internally, we get enough time to investigate more consistent optimizations in API or in the controller manager cache handling.
> Raise cache reload timeout limit

- hcloud/instances.go
- hcloud/instances_test.go
This is a quick-fix / enhancement for the issue described in https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/305
Switches the order of the node `ExternalIP` list to favour IPv4, as most of the dual-stack k8s clusters probably will be mostly relying on IPv4 control plane before apiserver properly supports dual-stack.
Signed-off-by: Rastislav Szabo <rastislav@kubermatic.com>
> Prioritize IPv4 address family by dual-stack

- deploy/ccm-networks.yaml
- deploy/ccm-networks.yaml.tmpl
- deploy/ccm.yaml
- deploy/ccm.yaml.tmpl
- deploy/dev-ccm-networks.yaml
- deploy/dev-ccm.yaml
When I tried to install [the latest ccm.yaml](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/deploy/ccm.yaml) onto a new Hetzner node running latest k3s + 1.22.7 I was surprised to get the following warning:
```
$ kubectl apply -f https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest/download/ccm.yaml
serviceaccount/cloud-controller-manager created
clusterrolebinding.rbac.authorization.k8s.io/system:cloud-controller-manager created
Warning: spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead
deployment.apps/hcloud-cloud-controller-manager created
```
This simple PR attempts to use the recommended replacement API.
Because the `critical-pod` …
> Migrate to priorityClassName API

- hcloud/cloud.go
allow users to disable networks routes (enabled by default), this can be useful if user use flannel with internal network, managing routes in this scenario does not needed.
disabling network routes also reduce calls to Hetzner API
Signed-off-by: Maksim Paskal <paskal.maksim@gmail.com>
> Flag to disable network routes

- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_test.go
> Fix PTR update for load balancer

- .github/workflows/test_e2e.yml
- .gitlab-ci.yml
- README.md
Add support for v1.26 and drop support for v1.22, in accordance with our Kubernetes version support policy (last 3 releases, same as upstream).
> feat: test against Kubernetes v1.26

- .github/workflows/test_e2e.yml
Logging the (temporary) API token here is unnecessary and potentially allows attackers to deploy malicious payloads in the Hetzner Cloud project associated with this repo, until the token is deleted and the resources are cleaned up.
> ci: stop logging api token

- .github/CODEOWNERS
- .gitlab/CODEOWNERS
- CODEOWNERS
Update the CODEOWNERS files to use the integrations group on GitHub and our company internal GitLab. This way we do not have to keep the files up to date manually in every repository, but instead we can just update the respective groups.
> chore: update codeowner to use groups

- deploy/ccm-networks.yaml
- deploy/ccm-networks.yaml.tmpl
- deploy/ccm.yaml
- deploy/ccm.yaml.tmpl
- deploy/dev-ccm-networks.yaml
- deploy/dev-ccm.yaml
… not NoSchedule
See
https://github.com/kubernetes/kubernetes/blob/4dd887797fe53816faf3cd4d65d600a606714f5d/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L77
> fix(deploy): node.kubernetes.io/not-ready taint is NoExecute

- README.md
We stated that the flag `--cloud-provider=external` is only required for Kube <=1.22, but it is actually still required in 1.26 and was never removed. This has caused confusion with users.
> docs: incorrect statement that --cloud-provider is removed

- e2etests/testing.go
The load balancers return a status code 503 if none of the targets have passed the health checks. Our test suite failed if it received anything but a 200. By also accepting a 503 and just continuing the wait we can get rid of one of the test failures.
> test(e2e): fix flake when LB health checks have not passed

- .github/workflows/test_e2e.yml
- .gitlab-ci.yml
- README.md
Remove Kubernetes v1.23 from CI tests and mark the latest released version in README.
This is in accordance with our Kubernetes Support Policy which states that we support the latest three releases.
We should only merge this after 2023-02-28, when v1.23 is considered EOL bei upstream.
> feat: drop support for Kubernetes v1.23

- README.md
The skaffold guide was copied from the csi-driver repo and was not updated to reference HCCM instead.
> docs: fix skaffold guide

- docs/load_balancers.md
Document how to reference an existing load balancer for use with a `Service`. I also fixed some typos and formatting issues in the file.
Related to #351.
> docs(lb): reference existing lb #351

- chart/.helmignore
- chart/Chart.yaml
- chart/templates/clusterrolebinding.yaml
- chart/templates/deployment.yaml
- chart/templates/serviceaccount.yaml
- deploy/ccm.yaml
- scripts/generate-deployment-yamls.sh
chart templates created by running the following:
```
$ tail -n+2 deploy/ccm.yaml | kubectl slice -t '{{.kind | lower}}.yaml' -o chart/templates/
```
`generate-deployment-yaml.sh` is updated to then do the previous thing in reverse. That is, it runs `helm template chart` and the contents go in deploy/ccm.yaml
As a result of this change, deploy/ccm.yaml.tmpl is no longer needed.
In follow-up commits the dev and network flavors will be generated from the new chart, and the corresponding .tmpl files will go away.
> chore: initial basic helm chart

- .github/workflows/goreleaser.yml
- .gitlab-ci.yml
The "default" branch for the repository was renamed to "main" at some point in the past, but these references were missed.
At the moment we do not publish the `:latest` image tag for snapshots.
> fix(ci): main branch rename

- .goreleaser.yml
- scripts/generate-deployment-yamls.sh
Package Helm Chart and add it to the GitHub release artifacts
> feat: add packaged helm chart to release artifacts

- hcloud/instances_test.go
This should have tested all 4 cases as described in the names, but it looks like I accidentally copied over the same test case four times.
> test: use actual test cases

- .goreleaser.yml
There were [two issues](https://github.com/hetznercloud/hcloud-cloud-controller-manager/actions/runs/4407161651/jobs/7720443310#step:9:54) with the goreleaser config:
- The publishing step is executed once per artifact by default, we have two artifacts (`deployment-yamls`, `hcloud-cloud-controller-manager`). By setting the id we make sure that its only executed once.
- The CHART_REPO_REMOTE variable was not available in the script. Environment variables need to be explicitly passed to downstream commands in goreleaser.
> ci: fix goreleaser helm chart config

- scripts/publish-helm-chart.sh
We previously relied on the helm-charts repo to re-build the index. But this has problems:
- The gh-pages pipeline is not properly started because events created by the default GITHUB_TOKEN do not trigger pipelines (in the same repo).
- Adding the chart and re-indexing happens in two commits, slightly obfuscating the chain of events
- When running `helm repo index` it updates the created timestamp of all existing entries. While I have not seen any issues yet, there might be some clients that rely on this field.
> ci: build helm repo index

- .github/workflows/goreleaser.yml
The tags v1.14.0-rc.2 and v1.14.0 point to the same commit. Goreleaser always releases v1.14.0-rc.2 and we don't get a proper v1.14.0 release.
By specifying the release that goreleaser should handle, we can rely on Github to specify the correct tag for the current workflow.
> fix(ci): wrong version published when two tags point to same commit 

- .goreleaser.yml
- scripts/generate-deployment-yamls.sh
The path for the deployment files was changed in https://github.com/hetznercloud/hcloud-cloud-controller-manager/pull/375 but not updated here. This cause the v1.14.1 release to be missing the release artifacts until I manually uploaded them.
In the current release process we need to "publish" the release twice, once to create the tag and trigger `goreleaser`, and then a second time because goreleaser turned the release back into a draft.
We can just skip the drafting step and let goreleaser publish directly.
Simplify the command used to update the Chart version and add some comments.
> chore: multiple improvements to the release process

- hcloud/instances.go
We did not properly handle nil pointers returned from `lookupServer`.
Based on the current usage in `k/cloud-provider` the methods are called in these contexts:
- `InstanceShutdown` is only called for instances that actually do exist (as verified by a prior call to `InstanceExists`)
- `InstanceMetadata` is called without verifying that the instance exists, one call site accepts a nil InstanceMetadata, but the other does not.
Closes #398
> fix: handle nil servers in InstanceV2 #398

- chart/values.yaml
- deploy/ccm-networks.yaml
- deploy/ccm.yaml
Reduce the number of API requests coming from the routes controller by reducing the reconciliation interval from 10s to 30s.
This is only a temporary fix until we can properly refactor the routes controller to only reconcile when necessary.
Related to #395
> fix: many API requests from Routes controller

- hcloud/routes.go
- hcloud/routes_test.go
- tests/e2e/e2e_test.go
This is a two-part fix for #425.
Closes #425 
More details can be found in [this comment](https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/425#issuecomment-1525776879)
We previously required that the route we were about to delete [had a valid server](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/892c20e199e1aee64e731aa9f05e9320dfc5d1bd/hcloud/routes.go#L161-L169). This does not make sense because in most cases we delete the route precisely because the server was deleted.
We implemented a route cleanup in https://github.com/hetznercloud/hcloud-cloud-controller-manager/pull/238 that deletes all routes in the network that can not be mapped to the private IP of a node. This causes issues for users who create their own routes, e.g. to an alias IP. …
> fix(routes): Only delete routes in the Cluster CIDR

- .github/workflows/test_e2e.yml
- README.md
Closes #435 
Add tests for Kubernetes v1.27.
Additionally I cleaned up the versioning policy as we only test against k3s nowadays and the specific patch version of k3s is not really relevant and hard to keep up to date.
> test: verify against Kubernetes v1.27

- .github/workflows/release-please.yml
- CHANGELOG.md
- chart/Chart.yaml
- chart/templates/deployment.yaml
- deploy/ccm-networks.yaml
- deploy/ccm.yaml
Setup release-please to automate creating new tags according to semver rules.
Updated referenced versions to latest released version to fix #431, new version should be bumped automatically by release-please.
Backfill changelog entries that were only on GitHub Releases.
> ci: setup release-please

- renovate.json
- renovate.json5
release-please defines the deps type for commits, which will be put into its own [section in the changelog](https://github.com/googleapis/release-please/blob/2b56b2213c10c6a0d3265746b10b19fbfce47292/src/changelog-notes.ts#L42-L55). This commit changes the default renovate commit message to use the deps type instead.
- Before: `fix(deps): update module github.com/prometheus/client_golang to v1.15.1`
- After: `deps: update module github.com/prometheus/client_golang to v1.15.1`
This helps declutter the "Bug Fixes" section in the changelog & release notes, so actual bug fixes are easier to review for users.
> chore: match renovate commits with release-please

- .github/workflows/release-please.yml
The default token GH_TOKEN in workflows does not trigger new events. We rely on the "tag" event created by release-please to build our release assets.
By using a token for "hcloud-bot", the event will be properly created.
We explicitly only run the workflow job if the repository is the main repo, as otherwise this workflow will fail in forks because the secret is not available.
See also hetznercloud/cli#476
> ci: fix release assets not available

- .github/workflows/goreleaser.yml
CI is currently [installing Go 1.2](https://github.com/hetznercloud/hcloud-cloud-controller-manager/actions/runs/4958991607/jobs/8872533527), which incidentally does not have `go mod` support 🙈
> chore(ci): fix go version in goreleaser workflow

- .github/workflows/test_e2e.yml
- tests/e2e/e2e_test.go
- tests/e2e/testing.go
While migrating this project from TTS -> TPS we switched the Hetzner
account. The new account does not have the domain `hc-certs.de`
configured. While the test case still succeeds (does not check for cert
status), we get lots of emails for the failed certificate issuance.
This commit makes the domain used in the test configurable and skips
the test in case no domain is set.
> test: use configurable domain for managed certificate

- .github/workflows/ci.yml
- .gitlab-ci.yml
- .golangci.yaml
A new version of golangci-lint updated depguard, which in turn started returning errors because it was missing a config. Previously depguard did not do anything as we never configured a list of allowed/denied imports.
In general, we already have gomodguard for linting imports.
To avoid sudden breakages of our CI in the future, I pinned the exact version of golangci-lint to the current release. Upgrading this should happen through a PR process (e.g. by renovate) so we can notice new linting failures and fix them before merging to main.
> ci: fix linting issues

- chart/templates/clusterrolebinding.yaml
- chart/templates/deployment.yaml
- chart/templates/podmonitor.yaml
- chart/templates/serviceaccount.yaml
- skaffold.yaml
This should fix the issue that you can change the release namespace with helm, but the deployment will not take care of it. 
Also this allows the user to use the nameoverwrite that was already defined inside the chart helpers.
> fix(helm-chart): resource namespace and name

- chart/templates/podmonitor.yaml
- chart/values.yaml
This PR adds the ability to set labels and annotations to the podMonitor. Setting the label is usually necessary for the podMonitor to be picked up by the Prometheus Operator (https://github.com/prometheus-operator/prometheus-operator/issues/3636#issuecomment-796688902). Setting an annotation helps to defer the deployment of the custom resource if e.g. deploying with ArgoCD (https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types).
> feat(helm): allow to set labels and annotations for podMonitor

- .goreleaser.yml
The helm chart was not published since 1.15.0. The script was not even called, because a change between 1.15.0-rc.0 & 1.15.0 caused the archive step to not be executed anymore.
As we never did anything with the archive anyway, I have removed it now.
Instead we ensure the "execute once" requirement for the chart publish by depending on the checksum output.
Closes #460
> ci: fix helm chart publishing

- deploy/ccm-networks.yaml
- deploy/ccm.yaml
- scripts/generate-deployment-yamls.sh
The command to generate the manifests was missing a namespace. This caused the manifests to have resources in namespace "default" which is not intended and a breaking change.
Fixes #475
> fix(deploy): manifests have wrong namespace "default"

- chart/templates/clusterrolebinding.yaml
- deploy/ccm-networks.yaml
- deploy/ccm.yaml
This is the last resource whose name was not configurable through the helm name override.
> fix(deploy): make last resource name configurable

- .github/workflows/ci.yml
- .goreleaser.yml
- scripts/release-generate-deployment-yamls.sh
- scripts/update-deployment-yamls.sh
We had some issues where the committed files in deploy/ did not match the files included with releases. This job makes sure that the files in deploy/ always match the current output from running "helm chart template".
[Example pipeline that demonstrates the output](https://github.com/hetznercloud/hcloud-cloud-controller-manager/actions/runs/5597677338)
Related to #476.
> ci: check deployment manifests

- .github/workflows/ci.yml
The current rules will create all the jobs in ci.yml twice for PRs. Once with the pull_request event, and then once again because the commit was pushed. This is annoying and wastes CI resources.
This fixes it by only running for PRs and pushes to main (instead of all branches). The same config is already used for the e2e tests.
> ci: only run ci.yml once per PR

- .gitlab-ci.yml
Use the new runner tags by using the default ci template.
> ci: use shared default template for ci tags

- chart/values.yaml
- deploy/ccm-networks.yaml
- deploy/ccm.yaml
Our dependency `k/cloud-provider` started binding this port in version 0.27.0 to serve webhooks from. We are not using the webhook feature and the port bind is causing conflicts for deployments that use the native networking feature (which enables `hostNetwork`).
See also:
- https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/492
- https://github.com/kubernetes/kubernetes/issues/120043
> fix(deploy): do not bind webhook port 10260

- .github/workflows/test_e2e.yml
- README.md
In line with our [Kubernetes Versioning policy](https://github.com/hetznercloud/hcloud-cloud-controller-manager?tab=readme-ov-file#versioning-policy).
> feat: test against kubernetes v1.28 and drop v1.24

- hack/dev-up.sh
The e2e tests fail regularly with error message:
hcloud: network 3334615 has no free IP available or is in a different network zone (invalid_input)
As far as I can tell, this happens because the network does not yet have an available subnet when the server is created. With this change, we will wait until the network has the subnet (by grepping for the subnet cidr) before creating the server.
Related to https://github.com/hetznercloud/csi-driver/pull/492
> ci: fix flake in dev/e2e env where subnet is not available

- hcloud/load_balancers.go
- hcloud/load_balancers_test.go
- internal/annotation/load_balancer.go
Fixes: https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/506, https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/373
> feat(load-balancer): Add new node-selector annotation

- hack/dev-up.sh
Any agents that were added to the dev env cluster (INSTANCES>1) would fail to initialize because they were being passed server-specific flags.
This commit moves these flags to the server only.
> chore(dev-env): fix issue with k3s flags on agents

- chart/README.md
- chart/templates/daemonset.yaml
- chart/templates/deployment.yaml
- chart/values.yaml
This adds the ability to run hccm as a `DaemonSet` like other cloud controller managers. 
There are also nodeSelectors as a new value to set where the DaemonSet (and deployment) should run. 
The default deployment kind of `Deployment` with 1 replica is not touched. 
The new configuration options are documented in the README file.
> feat(chart): add daemonset and node selector

- hack/dev-down.sh
- hack/dev-up.sh
**[chore(dev): clean all files related to dev env in hack/dev-down.sh](https://github.com/hetznercloud/hcloud-cloud-controller-manager/commit/0577061d03cd4005bb80a276666af9557e153343)**
The left-over files sometimes caused issues when the environment was re-deployed.
**[chore(dev): fix issue when helm install fails](https://github.com/hetznercloud/hcloud-cloud-controller-manager/commit/b1c4d3a69af7a3a23242daedd7acd87b653e1759)**
While `helm status` checks for a successful install, `helm install` will fail when a pre-existing failed install exists. By using `helm upgrade -install` the install will be retried if it previously failed.
> chore(dev): fix multiple issues in dev environment scripts

- .github/workflows/ci.yml
- .github/workflows/test_e2e.yml
- .gitlab-ci.yml
- README.md
- tests/e2e/e2e_test.go
- tests/e2e/testing.go
Add the build tag `e2e` to differentiate the long running e2e tests from shorter unit tests. This way we do not need to keep track of which files have which tests and the default "go test ./..." only executes the fast unit tests.
> refactor: use build tags to differentiate test suites

- .gitlab-ci.yml
- chart/values.yaml
- deploy/ccm-networks.yaml
- deploy/ccm.yaml
- hcloud/cloud.go
- hcloud/cloud_test.go
This variable is unused. It does not matter where HCCM is running, as long as it can talk to the Kubernetes & Hetzner Cloud APIs.
> feat: remove unused variable NODE_NAME

- hcloud/cloud.go
- hcloud/cloud_test.go
- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_test.go
The struct `LoadBalancerDefaults` was a subset of `config.LoadBalancerConfiguration` and unecessary.
Also remove a duplicate test.
> refactor: replace LoadBalancerDefaults with cfg

- .github/workflows/ci.yml
- Remove CI job already covered by golangci-lint
- Add a renovate regex comment to renovate the golangci-lint version
- Cleanup/Simplify
> ci: improve lint and test jobs

- hcloud/cloud.go
- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_test.go
This will be required for Robot support, as the LBOps code will need to know wether Robot support is enabled or not.
Related to #525 #549
> refactor: use full cfg in lbops

- hcloud/cloud.go
- internal/config/config.go
- internal/config/config_test.go
Clean up the config logic to be reuasble in other parts of the code.
> refactor: only enable routes if network name or id is configured

- .github/workflows/goreleaser.yml
Since reworking the docker build process in #417 we do not have a ":latest" image to push. The CI pipeline in main has failed since then.
Getting a "latest" image is not that easy with the current goreleaser setup. We use the goreleaser docker_manifests feature to build multi-arch images. This stage is not executed in "--snapshot" builds.
Example CI failure: https://github.com/hetznercloud/hcloud-cloud-controller-manager/actions/runs/5461797507/jobs/9940263986
> ci: fix failure on main when pushing latest image

- .github/workflows/test_e2e.yml
Download and save relevant logs generated during the e2e tests to make debugging them easier. Right now we have no visibility into the cluster, which makes debugging impossible and we always need to replicate locally before getting any kind of useful insights.
Saved data includes:
- Logs of HCCM Pods
- Any kind of Events generated in Kubernetes
The data is made available through GitHub Actions artifacts.
Split the large job into multiple smaller jobs doing distinctive things.
This helps with a bug in the GitHub Actions UI, where the logs sometimes do not load. With separate jobs you at least know where in the process you are.
> ci(e2e): persist logs for improved observability (#562)

- chart/templates/daemonset.yaml
- chart/templates/deployment.yaml
- deploy/ccm-networks.yaml
- deploy/ccm.yaml
This reverts commit 2c8378647923d3758bef63bc96dd83c5cb422f85 / #560.
The commit caused a regression where clusters not using the host network were unable to bootstrap successfully:
- CoreDNS did not start because the Node was still tainted as uninitalized
- HCCM could not initialize the Node because it failed to resolve the DNS entry for "api.hetzner.cloud".
> fix(deployment): revert #560: remove dns-policy

- .github/workflows/release-please.yml
Instruct `release-please` to skip the pre-release tag `1.19.0-rc.0` when building the changelog for the next release, and force it to create a new release called `1.19.0` next.
> chore: prepare 1.19.0 release

- README.md
Kubernetes now regularly has 4 active releases. In practice we only remove the release once it has officially been marked EOL, and not when a new release is published.
> docs: update versioning policy to match reality

- .github/workflows/test_e2e.yml
- README.md
Also updated the version matrices to use "latest" vs "main". We do not support any builds from the "main" branch, and this was always intended to tell the user to use the latest published release for these versions.
> feat: add support & tests for Kubernetes 1.29

- hcloud/cloud.go
- hcloud/cloud_test.go
- hcloud/instances.go
- hcloud/instances_test.go
- hcloud/routes.go
- internal/hcops/load_balancer.go
- internal/hcops/testing.go
`k/cloud-provider` emits Events for most errors we return. In some conditions we previously hid the errors from `k/cloud-provider` for various reasons and only logged a warning. This is hard to discover for users. With this change, we now also emit Kubernetes Events for these cases.
> feat: emit Kubernetes events for error conditions

- README.md
- Mention that the deployment suggestions for the flag are only valid for `kubeadm` and other distributions might have different requirements
- Mention the kubeadm config field that can be used in place of the systemd drop-in unit.
- Update deprecation notice for flag `--cloud-provider=external` for latest kubernetes release.
Closes #513
> docs(deploy): mention kubeadm config for --cloud-provider flag

- .github/workflows/test_e2e.yml
- hack/dev-up.sh
Hardcode versions of k3s to the last versions before the broken behaviour was introduced. We plan to unpin the versions after we figure out where the bug is coming from and fix it upstream.
> test(e2e): new k3s versions break our dev/e2e test setup

- docs/robot.md
Correct the name of the environment variable in the robot docs.
> docs(robot): fix typo

- .github/workflows/ci.yml
- .github/workflows/goreleaser.yml
- .github/workflows/test_e2e.yml
Use the `go.mod` file to determine the version of go to run in CI.
> ci: setup go version using go.mod file

- .github/workflows/test_e2e.yml
Update e2e test tools, except kubectl, to the latest version.
> ci: update helm and skaffold for e2e tests

- chart/templates/daemonset.yaml
- chart/templates/deployment.yaml
- chart/values.yaml
- internal/config/config.go
- internal/config/config_test.go
- internal/testsupport/files.go
This allows the `HCLOUD_TOKEN` (and `ROBOT_USER` and `ROBOT_PASSWORD`) to be read from a file. This can be useful if the token is injected using secret injection (e.g. with the vault agent injector).
I tested the changes on my dev cluster. I cannot test the robot account changes, because I only use hcloud. But because they use the same function inside the code I think its working too :). If someone is interested in using this with the vault agent injector, I used the following helm values:
```yaml
image:
repository: <custom-image-because-changes-are-not-released>
tag: <custom-image-because-changes-are-not-released>
podAnnotations:
vault.hashicorp.com/agent-inject: "true"
vault.hashicorp.com/log-format: json
vault.hashicorp.com/role: <your-vault-role-name> …
```
> feat: read HCLOUD_TOKEN from file

- README.md
Learn more: https://docs.hetzner.cloud/changelog#2024-06-06-old-server-types-with-shared-intel-vcpus-are-deprecated
- Updated docs with newer server types
> chore: replace deprecated server type with cx22

- hack/robot-e2e/ansible.cfg
The interpreter discovery will set the python path to e.g. /usr/bin/python3.11 on ubuntu 24.04, but after reinstalling and rebooting the system to an older version e.g. ubuntu 24.04 => ubuntu 22.04, the previously discovered path will be invalid.
This ensures we use a non versioned path to python3.
> ci: prevent interpreter discovery to fail across distribution release

- README.md
This will always use the latest flannel release, not the main branch. Pointing to an exact version would keep the documentation to a version that might not work for users in the future.
The snippet is from Flannel's README.
> docs: Always use latest flannel release

- .github/workflows/test_e2e.yml
- README.md
Kubernetes v1.26 is End of Life since 2024-02-28. In accordance with our Versioning policy.
> feat: drop tests for kubernetes v1.26

- go.mod
- hcloud/routes.go
- internal/hcops/server.go
- internal/hcops/server_test.go
Fixes #673
In `routes.ListRoutes()` we have to find the matching server/node for every route in the network. We find the server by utilizing a cache that maps every private IP to the corresponding server.
This cache has a feature that refreshes the list of servers if an entry can not be found. This is sensible, as the server might have been just created. This is also fatal, as this refresh happens for every single cache access. If there are a lot of routes in the network that do not belong to any server, we refresh the cache many times for each `ListRoutes()`. This is even more serious, as `ListRoutes()` is being called every 10-30 seconds (see #395).
This commit introduces a `rate.Limiter` in the `AllServersCache` which only allows the refresh to happen every 30 seconds.
> fix(routes): many requests for outdated routes by rate limiting

- skaffold.yaml
We changed the image reference in a recent PR. With this, skaffold was unable to match it against the image referenced in the Helm chart, so it always deployed the tagged version of the image.
This caused all e2e tests to not use the actual changes made in those PRs.
Noticed this because the release-please PR was trying to pull a `v1.20.0` image and failed.
> chore: skaffold was not using the built image

- chart/templates/deployment.yaml
- chart/values.yaml
Support setting the Affinity for pods of the `Deployment`.
> feat(helm): allow setting affinity for deployment

- skaffold.yaml
In our dev/test environment we deploy a container registry to the cluster and push our image there to avoid a dependency on external registries.
To pull from the registry, containerd is instructed to use the service IP. This IP is resolved to the Pod IP in kube-proxy. The CNI is then responsible for making a connection to the Pod IP.
In our case we have the CNI configured to use the Cloud Routes for accessing the Pod IPs from other nodes. This is only being setup by HCCM, which is a problem if we need the routes for pulling the HCCM container image.
This fixes the circular dependency by running HCCM on the same node as the registry. That way no external routes are required and the traffic stays on the same node.
This is not a problem on clusters where HCCM is pulled from an external …
> ci: fix flaky e2e tests by colocating registry & hccm

- chart/values.yaml
- deploy/ccm-networks.yaml
- deploy/ccm.yaml
- skaffold.yaml
Mostly to make sure we are consistent with our other kubernetes integration: csi-driver.
> chore: use fully qualified container name

- chart/templates/deployment.yaml
- deploy/ccm-networks.yaml
- deploy/ccm.yaml
The container image already has the entrypoint defined. It makes no sense to duplicate this in the deployment manifests.
The hardcoded entrypoint has stopped us from introducing ko for building container images before, as ko uses another entrypoint and has no option for configuring it.
> feat(helm,manifests): only specify container args instead of command

- hcloud/load_balancers.go
- hcloud/load_balancers_test.go
Closes #553
Refactor getting the ingresses for a load-balancer for both get load-balancer and ensure load-balancer, into using a shared function. This ensures we are consistent between the 2 methods.
Release notes:
The load balancer ingress IPs are now populated with the private IPs, unless the `load-balancer.hetzner.cloud/disable-private-ingress` annotation is set to `true`. Please make sure that you configured the annotation according to your needs, for example if you are using `external-dns`.
> fix: populate ingress private ip when disable-private-ingress is false

- .goreleaser.yml
The k/cloud-provider library is logging a version on startup. This version is expected to be set by Kubernetes build scripts, but we do not use this.
Right now it looks like this:
```
controllermanager.go:169] Version: v0.0.0-master+$Format:%H$
```
With the fix, this will report the same version as we use for the user-agent.
> fix: wrong version logged on startup

- hcloud/load_balancers.go
- internal/annotation/load_balancer.go
- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_test.go
Allows users to specify the IPv4 of the load balancer in the private network via the annotation "load-balancer.hetzner.cloud/private-ipv4"
Removes network logic from main load balancer creation, since the API does not support specifying the IP address there, and moves network logic to exclusively happen in AttachToNetwork and DetachFromNetwork.
I also added an extra LoadBalancer refresh in the main reconciliation loop, since changing the IP address of an SVC object causes network detach and subsequent attach, which in turn needs to cause the targets to be re-added to loadbalancer if they were private network targets.
Unit tests pass and i have tested this in a few scenarios on a cluster of my own.
> feat(service): Specify private ip for loadbalancer

- .github/workflows/test_e2e.yml
- README.md
Kubernetes v1.27 is End of Life since 2024-07-16. In accordance with our Versioning policy.
> feat: drop tests for kubernetes v1.27

- chart/templates/daemonset.yaml
- chart/templates/deployment.yaml
- chart/values.yaml
This adds the ability to set `extraVolumes` and `extraVolumeMounts` via helm to the pod. It can be used to mount extra files, to persist files inside the container or to allow usage of the CSI Secret Driver.   
It does not introduce user facing changes since the default for both is an empty array, so no volumes or volumeMounts are created when not explicitly set. 
Fixed #743 
The change can be previewed with the following command: `helm template chart -s templates/deployment.yaml --values chart/my-values.yaml --debug`
```yaml
extraVolumeMounts:
- name: token-volume
readOnly: true
mountPath: /var/run/secrets/hcloud
extraVolumes:
- name: token-volume
secret:
secretName: hcloud-token
env:
HCLOUD_TOKEN_FILE:
value: /var/run/secrets/hcloud/token
HCLOUD_TOKEN: null
```
Testing can be done with …
> feat(helm): allow setting extra pod volumes via chart values 

- README.md
- docs/robot.md
- hcloud/instances.go
- hcloud/instances_test.go
- tests/e2e/cloud_test.go
- tests/e2e/robot_test.go
This update to the HCCM introduces a new label for Kubernetes nodes: `instance.hetzner.cloud/provided-by`. This label will be automatically applied to nodes, indicating their origin as either:
- `robot` for dedicated servers
- `cloud` for cloud-based virtual machines
With this features other components (e.g. csi-driver) can fine-tune their deployment requirements.
> feat(instance): add label to distinguish servers from Cloud and Robot

- hcloud/instances_test.go
- hcloud/instances_util.go
Invalid characters like `™` should be removed when generating the instance-type label for Robot servers.
> fix: invalid characters in label instance-type of robot servers

- hcloud/instances.go
- hcloud/instances_util.go
When the Robot server name is changed in the Robot console or via the API the node might be deleted by the node-lifecycle-manager. We now emit a warning event for this case.
> feat: emit event when robot server name and node name mismatch

- .golangci.yaml
- hcloud/load_balancers_test.go
- internal/annotation/load_balancer_test.go
- internal/annotation/name_test.go
- internal/hcops/certificates_test.go
- internal/hcops/load_balancer_internal_test.go
- internal/hcops/load_balancer_test.go
Updated golangci-lint configuration and resolved all linting issues identified by the updated settings.
> style: replaced deprecated linter exportloopref with copyloopvar

- hcloud/cloud.go
- hcloud/cloud_test.go
- main.go
Removed the `cloudprovider.InitCloudProvider` initialization process to simplify the codebase and enhance maintainability.
> refactor: simplified hccm init code

- hcloud/cloud.go
- hcloud/cloud_test.go
- hcloud/routes.go
- hcloud/routes_test.go
- main.go
Before adding a route, verify if the route CIDR is contained within the configured cluster CIDR. If it is not, emit a warning event and log message.
> feat(routes): emit warning if cluster cidr is misconfigured

- hcloud/instances.go
- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_test.go
- internal/providerid/providerid.go
- internal/providerid/providerid_test.go
With this feature the load balancer is more resilient to hybrid clusters as it skips nodes with unkown provider ids.
> feat(load-balancer): ignore nodes that don't use known provider IDs

- chart/Chart.yaml
`release-please` automatically found and updated the file, this no longer works with `releaser-pleaser` and it requires the marker.
> ci: fix missing version update in Chart.yaml

- internal/metrics/metrics.go
This includes metrics about internal operations from `k8s.io/cloud-provider` like the workqueue depth and requests to the Kubernetes API.
This metrics were already exposed on `:8233/metrics` but this was not documented or scraped.
This commit now uses the same registry for our metrics and the Kubernetes libraries, and also exposes them on both ports for backwards compatibility.
Besides having all data available, this will also help us with debugging #661.
> feat(metrics): add metrics from cloud-provider library

- .github/workflows/ci.yml
- .pre-commit-config.yaml
Added golangci-lint run hook to pre-commit configuration and removed separate CI step.
> ci: added golangci-lint to pre-commit

- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_test.go
If an unsupported port protocol is configured a warning event and log message is emitted.
> feat(load-balancer): emit warning if unsupported port protocol is configured

- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
- main.go
Because `kubernetes_build_info` reports the version of the HCCM and not Kubernetes, we are removing it from the metrics registry. This happens because the intended use of `k8s.io/compeonent-base/metrics` expects us to follow the Kubernetes release cycle and versioning. As the metric is initialized in the `k8s.io/component-base/metrics/prometheus/version` package, we can just remove the import.
This was discovered through alerts being raised by the default alert rule `KubeVersionMismatch` of the `kube-prometheus-stack`.
> fix(metrics): do not emit kubernetes_build_info metric

- docs/load_balancers.md
#845 faced an issue, where confusing documentation lead to a deployment issue.
> docs(load-balancer): correct description of load-balancer destination port

- .pre-commit-config.yaml
As there was no `depName` defined with the `golang-version` `datasource`, our custom Renovate regex manager did not detect this as a dependency. We can also use the git tags from the official repository as [`golang-version`](https://docs.renovatebot.com/modules/datasource/golang-version/) is using this as a source AFAIK.
Question is, if we really need this check at all. Pre-commit will use the newest Golang version by default, which should be sufficient as `golangci-lint` will use the go version specified in the `go.mod`.
> ci: fix pre-commit golang version

- .github/workflows/ci.yml
- .pre-commit-config.yaml
Fixes pre-commit CI pipeline of #881.
> ci: fix golangci-lint using go toolchain version in pre-commit

- renovate.json
Co-authored-by: jonas.lammler@hetzner-cloud.de
> ci: group golang deps in renovate

- renovate.json
This reverts commit 657b088ca1c373fc7fb999a401472f92fddc964d.
> ci: revert group golang deps in renovate (#886)

- docs/how-to-robot-vswitch-load-balancer.md
- internal/hcops/load_balancer.go
This feature enables the annotation `load-balancer.hetzner.cloud/use-private-ip` for clusters that include Robot servers.
We recently introduced forwarding configured InternalIPs of Robot nodes (#865). With this addition we can use these IPs and configure them as load balancer targets, when `load-balancer.hetzner.cloud/use-private-ip` is set.
> feat(load-balancer): enable use-private-ip annotation for Robot servers

- tests/e2e/cloud_test.go
In #928 a boolean got flipped. Probably a copy-paste error.
This caused the test to wait for an HTTP service to be available in an HTTPS test.
> test: fix waiting for an HTTP service to be available in an HTTPS test

- CHANGELOG.md
Because of a currently unknown issue no tag was created through `releaser-pleaser`. This left us with a CHANGELOG entry and release without artifacts. Rerunning `releaser-pleaser` solved the issue, but created a duplicated CHANGELOG entry.
> chore: fix duplicated CHANGELOG entry

- internal/annotation/load_balancer.go
All domains specified via the annotation `load-balancer.hetzner.cloud/http-managed-certificate-domains`, are used to create a single managed certificate. Therefore, the annotation `load-balancer.hetzner.cloud/http-managed-certificate-name` only accepts one name.
Additionally, fixed a small typo.
> docs: fix certificate name plural

- chart/values.yaml
- docs/reference/helm/extra-envs.md
Be more precise in the values documentation about how to set extra environment variables. Update existing docs with upstream references to most common usages.
Fixes #951
> docs(helm): extra environment variables format

- .goreleaser.yml
- scripts/publish-helm-chart.sh
All artifacts must have a non empty ID, otherwise the `ids: [""]` filter will include artifacts with an empty ID (strings in go are initialized to "").
Add an ID to all artifacts to prevent running in the problem described abovei and filter all IDs using a unused ID ("none") in the helm chart publisher.
In addition, do skip publishing the helm chart if the chart file already exists in the chart repository.
> ci: ensure goreleaser chart publish script runs only once
