hetznercloud/hcloud-cloud-controller-manager

- docs/deploy_with_networks.md
I have updated a link, so yoiu do not get a 404 Not Found anymore...
> Correct wrong README link in documentation

- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_internal_test.go
> Parse interval and timeout as time.Duration

- CHANGELOG.md
- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_internal_test.go
- internal/hcops/load_balancer_test.go
> Fix health check defaults

- CHANGELOG.md
- go.mod
- go.sum
- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_internal_test.go
- internal/hcops/load_balancer_test.go
> Update default health check

- CHANGELOG.md
- hcloud/load_balancers.go
- hcloud/load_balancers_test.go
> Ignore protected Load Balancers at deletion instead of raising an error.

- CHANGELOG.md
- hcloud/routes.go
- internal/hcops/server.go
- internal/hcops/server_test.go
- internal/mocks/server.go
Internal reference: closes #48
> Add cache for cluster servers

- .github/workflows/test_e2e.yml
- .gitlab-ci.yml
- scripts/e2etest-local.sh
v1.17.14 & v1.19.4 were released yesterday. v1.18.11 was also already tagged but not released yet. 
I will undraft this MR when v1.18.11 is ready too.
> Update k8s version we test against to latest minor release

- e2etests/e2e_test.go
- e2etests/setup.go
- e2etests/testing.go
- hcloud/cloud.go
- internal/annotation/name.go
- internal/annotation/name_test.go
- internal/hcops/certificates.go
- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_test.go
- internal/hcops/testing.go
- internal/mocks/casts.go
- internal/mocks/certificates.go
- internal/testsupport/tls.go
> Reference certificates by name

- CHANGELOG.md
- docs/load_balancers.md
- hcloud/cloud.go
- hcloud/cloud_test.go
- hcloud/load_balancers.go
- hcloud/load_balancers_test.go
- hcloud/testing.go
- internal/hcops/load_balancer.go
- internal/hcops/load_balancer_test.go
> Loadbalancer: Support setting defaults

- .github/workflows/goimports.yml
- .github/workflows/publish_on_master.yml
- .github/workflows/publish_on_tag.yml
- .github/workflows/test.yml
- .github/workflows/test_e2e.yml
- .gitlab-ci.yml
- CHANGELOG.md
- Dockerfile
- README.md
- go.mod
> Use Go 1.16

- CHANGELOG.md
- go.mod
- go.sum
> Update hcloud-go to v1.24.0

- hcloud/routes.go
- internal/hcops/server.go
- internal/hcops/server_test.go
> Fix cache issue in CreateRoute

- deploy/ccm-networks.yaml.tmpl
- deploy/ccm.yaml.tmpl
When switching to generated deployment yamls the change was not
migrated.
> Add #190 to yaml templates

- .goreleaser.yml
> Fix glob for deployment yamls

- README.md
Adding the Networks explanation from https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/164 to the readme
> Update README.md to include Networks support

- docs/load_balancers.md
Adding important note for IPVS users
> Improving documentation

- hcloud/util.go
> Fix typo in log message

- README.md
https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/212
> Update README for kube-proxy IPVS information

- .github/workflows/goimports.yml
- .github/workflows/goreleaser.yml
- .github/workflows/test.yml
- .github/workflows/test_e2e.yml
- .gitlab-ci.yml
- README.md
- go.mod
> Build and test with go 1.17

- e2etests/.gitignore
- e2etests/setup.go
- e2etests/templates/cloudinit_k3s.txt.tpl
- e2etests/templates/cloudinit_k8s.txt.tpl
- e2etests/testing.go
This allows creating clusters in our tests with multiple (worker) nodes.
> Testsetup: Unify with CSI Driver test setup suite

- e2etests/testing.go
- go.mod
- go.sum
> Update hcloud-go to v1.33

- .github/workflows/goimports.yml
- .github/workflows/goreleaser.yml
- .github/workflows/test.yml
- .github/workflows/test_e2e.yml
- .gitlab-ci.yml
- README.md
- go.mod
- go.sum
> Use Go 1.18

- .github/workflows/goimports.yml
- .github/workflows/goreleaser.yml
- .github/workflows/test.yml
- .github/workflows/test_e2e.yml
- .gitlab-ci.yml
- README.md
- go.mod
> Update to Go 1.19

- .github/workflows/test_e2e.yml
- README.md
> Add support for k8s 1.25

- go.mod
- go.sum
> Update hcloud go to v1.35.3

- chart/README.md
- chart/templates/deployment.yaml
- chart/values.yaml
- deploy/ccm-networks.yaml
- deploy/ccm.yaml
This adds configurable replicas to the helm chart.
> feat(charts): add replica count

- .github/workflows/ci.yml
- .github/workflows/goreleaser.yml
- .github/workflows/test_e2e.yml
- .gitlab-ci.yml
- README.md
- go.mod
- hack/Dockerfile
Also bump golangci-lint to v1.54.2.
> feat: build with Go 1.21

- chart/templates/deployment.yaml
- chart/values.yaml
> feat(chart): configure additional tolerations

- hcloud/cloud.go
It is way simpler to keep all logic related to the individual controller interfaces in their respective methods, instead of creating 2 (InstanceV2, LoadBalancer) interfaces in `hcloud.newCloud()` and 1 (Route) in the accessor function.
> refactor: move client init out of newCloud()

- hack/dev-up.sh
This feature will not work with the new Robot integration, so we need to make it optional in the dev env.
Related to #526
> chore(dev-env): make private network routes feature optional

- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
Setup proper timeouts for metrics server
> chore(metrics): add timeouts for metrics server

- chart/templates/daemonset.yaml
- chart/templates/deployment.yaml
- deploy/ccm-networks.yaml
- deploy/ccm.yaml
> fix(deployment): remove dns-policy

- README.md
- chart/values.yaml
- docs/robot.md
- Add documentation for the features introduced in #561.
- Cleans up some other documentation fragments that have become outdated with time.
Closes #528
> docs: describe new Hetzner Robot integration

- docs/deploy_with_networks.md
> docs: describe networks ip ranges with example

- .gitlab-ci.yml
- README.md
- go.mod
- hack/Dockerfile
Preparation work to be able to merge #619
> feat: build with Go 1.22

- internal/hcops/server.go
This separates accessing the cache from loading the data and renames some identifiers to better represent their purpose.
> refactor(hcops): cleanup AllServersCache

- .github/workflows/robot.yml
Prevent possible job cancelation when working on the HCCM project during the day.
> ci: run robot install workflow at 02:30 on Monday

- .github/workflows/ci.yml
- .goreleaser.yml
- .pre-commit-config.yaml
- README.md
- chart/README.md
- chart/templates/daemonset.yaml
- chart/templates/deployment.yaml
- chart/values.yaml
- deploy/kustomization.yaml
- docs/deploy_with_networks.md
- docs/load_balancers.md
- docs/robot.md
- scripts/publish-helm-chart.sh
- scripts/release-generate-deployment-yamls.sh
- scripts/update-deployment-yamls.sh
Ensure files are kept formatted using pre-commit.
Some manual changes were done to improve further the changes made by prettier or linting error by shellcheck.
> chore: add pre-commit setup 

- dev/Dockerfile
In my experience, this speeds up the build step quite a lot :)
> build: Improve go build caching

- hcloud/cloud.go
- hcloud/cloud_test.go
- hcloud/instances.go
- hcloud/instances_test.go
Refactor preparation for #859.
> refactor: configuration passing and NodeAddress validation

- chart/.snapshots/default.yaml
- chart/templates/deployment.yaml
- chart/values.yaml
- deploy/ccm-networks.yaml
- deploy/ccm.yaml
Set priorityClassName through Helm chart. Defaults to `system-cluster-critical`.
Requested in #848
> feat(helm): support custom priorityClassName

- chart/templates/daemonset.yaml
- chart/templates/deployment.yaml
- chart/values.yaml
Add additional `imagePullSecrets` to the deployment or daemonset via the value `image.pullSecrets`.
Requested in #874
> feat(helm): support imagePullSecrets

- .gitpod.yml
Gitpod is not used by the team and this file is unmaintained.
> chore: cleanup unused files
